<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>$(AssemblyName)</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\logo.png" Pack="true" PackagePath="" Link="logo.png" />
    <None Include="..\..\logo.ico" Pack="true" PackagePath="" Link="logo.ico" />
  </ItemGroup>
</Project>
